#自定义配置信息
foo: hello foo2#自定义配置信息
authProps:
  customerKey: a1s2d3f4
  #加密盐值
  salt: ${salt}
  #超时记录
  #recordTime: ${recordTime}
  #排除卡bin信息
  timeStampIgnore: false
  signEnabled: true
  allowDupOrder: true
  chance: 11.0
  sleepTime: 10
  excludeBin:
    - 622686
    - 622288
    - 628280
    - 622858
    - 621058
    - 621527
    - 623091
    - 621537
    - 621736
    - 623540
  excludeBinMap:
    16: 622686,622288,628280
    19: 622858,621058,621527,623091,621537,621736,623540
  #状态码map
  codeMsgMap:
    90: 认证成功
    91: 认证失败
    10: 报文格式错误
    101: 商户号为空或不是12位
    102: 签名为空或不是32位
    103: CHR-SET不是UTF-8
    104: 时间戳错误
    105: CUSTINFO为空
    106: 订单号为空
    107: BASE64解码错误
    11: 验签失败
    21: 商户号不存在
    22: 商户暂停服务
    23: 业务不存在
    24: 重复交易
    25: 余额不足
    31: 身份证格式不对
    32: 银行卡格式不对
    33: 手机号格式不对
    41: 系统繁忙
    42: 测试条目不足
    43: 异步url不可用
    44: 交易失败,请重试
    45: 交易失败,发卡行不支持
    60: 交易失败,请联系发卡行
    61: 银行卡号无效
    66: 持卡人身份信息或手机号输入不正确

